name: mboacare_admin
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  fl_chart: ^0.64.0
  get: ^4.6.6
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4
  flutter_spinkit: ^5.2.0
  image_picker: ^1.0.4
  file_picker: ^4.0.0
  provider: ^6.0.5
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  shared_preferences: ^2.2.2
  http: ^1.2.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter: 
  assets:
    - assets/icons/
    - assets/svg/
  uses-material-design: true
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 